data_config:
  dataset_directory: C:\Users\...
  sample_list_file_path: C:\Users\...
  batch_size: 9
  patch_size:
    x: 32
    y: 32
    z: 32
  oversample_foreground_percent: 0.33
  memmap_mode: "r"
  pad_mode: "edge"
  num_classes: 3

model_config:
  unet_num_layers: 3
  num_input_channels: 1
  base_num_features: 32
  load_model: False
  model_path: None

train_config:
  num_epochs: 100
  num_batches_per_epoch: 100
  num_val_batches_per_epoch: 100
  initial_learning_rate: 0.001
  weight_decay: 0.00003
  optimizer_momentum: 0.99
  max_norm_gradient: 2

loss_config:
  ds_loss_weights: None
  batch_dice: True

output_folder: C:\Users\...
